---
- name: Set up static site buckets on AWS as static s3 bucket
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Create S3 bucket
    amazon.aws.s3_bucket:
      name: 'www.{{s3bucket}}'
      state: present
      versioning: yes
  - name: Setup S3 Bucket as website
    community.aws.s3_website:
      name: 'www.{{s3bucket}}'
      state: present
      suffix: index.html
      error_key: errors/404.html
  - name: Add pages
    community.aws.s3_sync:
      bucket: 'www.{{s3bucket}}'
      file_root: 'files/{{s3bucket}}'
    tags:
      - debug
  - name: Create empty apex redirect bucket
    amazon.aws.s3_bucket:
      name: '{{s3bucket}}'
      state: present
      versioning: no
  - name: Setup redirect from apex to www.
    community.aws.s3_website:
      name: '{{s3bucket}}'
      redirect_all_requests: 'www.{{s3bucket}}'
      state: present
  - name: Create logs bucket
    amazon.aws.s3_bucket:
      name: 'logs.{{s3bucket}}'
      state: present
      versioning: no
  - name: setup logging
    community.aws.s3_logging:
      name: '{{s3bucket}}'
      state: present
      target_bucket: 'logs.{{s3bucket}}'
      target_prefix: 'logs/'
  - name: log cleanup 
    community.aws.s3_lifecycle:
      name: 'log.s{{s3bucket}}'
      transition_days: 7
      expiration_days: 90
      prefix: logs/
      status: enabled
      state: present
