---
- name: Set up static site buckets on AWS as static s3 bucket
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Create S3 bucket
    amazon.aws.s3_bucket:
      name: 'www.{% raw %}{{s3bucket}}{% endraw %}'
      state: present
      versioning: yes
  - name: Setup S3 Bucket as website
    community.aws.s3_website:
      name: 'www.{% raw %}{{s3bucket}}{% endraw %}'
      state: present
      suffix: index.html
      error_key: errors/404.html
  - name: Add pages
    community.aws.s3_sync:
      bucket: 'www.{% raw %}{{s3bucket}}{% endraw %}'
      file_root: '../files/{% raw %}{{s3bucket}}{% endraw %}'
    tags:
      - debug
  - name: create ACL file
    template:
      dest: /tmp/www.{% raw %}{{s3bucket}}{% endraw %}.acl.json
      src: ../files/www.public_s3.j2
  - name: Clear access controls www.
    shell:
      aws s3api put-bucket-policy --bucket 'www.{% raw %}{{s3bucket}}{% endraw %}' --policy 'file:///tmp/www.{% raw %}{{s3bucket}}{% endraw %}.acl.json'
  - name: Create empty apex redirect bucket
    amazon.aws.s3_bucket:
      name: '{% raw %}{{s3bucket}}{% endraw %}'
      state: present
      versioning: no
  - name: Setup redirect from apex
    community.aws.s3_website:
      name: '{% raw %}{{s3bucket}}{% endraw %}'
      redirect_all_requests: 'www.{% raw %}{{s3bucket}}{% endraw %}'
      state: present
  - name: create apex ACL file
    template:
      dest: /tmp/{% raw %}{{s3bucket}}{% endraw %}.acl.json
      src: ../files/public_s3.j2
  - name: Clear access controls apex
    shell:
      aws s3api put-bucket-policy --bucket '{% raw %}{{s3bucket}}{% endraw %}' --policy 'file:///tmp/{% raw %}{{s3bucket}}{% endraw %}.acl.json'
  - name: Create logs bucket
    amazon.aws.s3_bucket:
      name: 'logs.{% raw %}{{s3bucket}}{% endraw %}'
      state: present
      versioning: no
  - name: setup logging
    community.aws.s3_logging:
      name: '{% raw %}{{s3bucket}}{% endraw %}'
      state: present
      target_bucket: 'logs.{% raw %}{{s3bucket}}{% endraw %}'
