list_characters.gif: 
	x16emu.exe -bas ../../_includes/basic/specials.bas -gif list_characters.gif

latest.gif: 
	x16emu.exe -bas ../../_includes/basic/latest.bas -gif latest.gif

# make new FILE=colors
new: 
	x16emu.exe -bas ../../_includes/basic/$(FILE).bas -gif $(FILE).gif