name: Markdown to HTML

on:
  push:
    branches:
      - main 
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: update inventory mix and match  
          shell: pwsh
          run: ./update_mix_json.ps1

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: '21.x'
        - run: npm ci
        - name: clone dotfiles for examples
          uses: actions/checkout@v2
          with:
            repository: edthedev/dotfiles
            path: ./dotfiles
        - name: cleanup .git to avoid confusing GitHub's deploy automation
          run: |
            rm -rf ./dotfiles/.git

        - name: Build static site
          run: npx @11ty/eleventy

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            # deploy_key: ${{ secrets.DEPLOY_KEY }} - expects ssh rather than deploy key
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # external_repository: username/external-repository # Defaults to this repo
            publish_branch: gh-pages # default: gh-pages
            publish_dir: ./_site # default is public
            force_orphan: true # do not maintain history on gh-pages branch
            cname: edward.delaporte.us # restores the CNAME file to the output directory.
